fix: 경로 수정

diff --git a/.github/workflows/dev_deploy.yml b/.github/workflows/dev_deploy.yml
--- a/.github/workflows/dev_deploy.yml
+++ b/.github/workflows/dev_deploy.yml
@@ -1,4 +1,4 @@
-name: AECOCARM Dev CI/CD
+name: AECOFARM Dev CI/CD
 
 on:
   push:
@@ -8,42 +8,42 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest # (3).OS환경
-    if: github.ref == 'refs/heads/main'
+    runs-on: ubuntu-latest
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v2 # (4).코드 check out
+        uses: actions/checkout@v3
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
-          java-version: 17 # (5).자바 설치
+          java-version: 17
           distribution: 'adopt'
 
       - name: Grant execute permission for gradlew
         run: chmod +x ./gradlew
-        shell: bash # (6).권한 부여
 
       - name: Build with Gradle
         run: ./gradlew clean build -x test
-        shell: bash # (7).build시작
 
       - name: Get current time
         uses: 1466587594/get-current-time@v2
         id: current-time
         with:
           format: YYYY-MM-DDTHH-mm-ss
-          utcOffset: "+09:00" # (8).build시점의 시간확보
+          utcOffset: "+09:00"
 
       - name: Show Current Time
-        run: echo "CurrentTime=$"
-        shell: bash # (9).확보한 시간 보여주기
+        run: echo "CurrentTime=${{ steps.current-time.outputs.formattedTime }}"
 
       - name: Generate deployment package
         run: |
           mkdir -p deploy
-          cp build/libs/*.jar deploy/application.jar
+          cp build/libs/aecofarm-0.0.1-SNAPSHOT.jar deploy/application.jar
+          if [ ! -f deploy/application.jar ]; then
+            echo "JAR file not found, build failed."
+            exit 1
+          fi
           cp Procfile deploy/Procfile
           cp -r .ebextensions-dev deploy/.ebextensions
           cp -r .platform deploy/.platform
@@ -60,4 +60,3 @@ jobs:
           region: ap-northeast-2
           deployment_package: deploy/deploy.zip
           wait_for_deployment: false
-
